version: '3.8'

services:
  web:
    image: short_link:latest # 替换为您的实际镜像名称
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_DSN=root:123456@tcp(mysql:3306)/shortlink?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    networks:
      - app-network
    volumes:
      - ./config/app.yaml:/app/config/app.yaml # 挂载本地配置文件


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shortlink
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge